AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Parameters:
  Region:
    Type: String
    Default: ap-south-1
    Description: The region to deploy the code to.
  EnvStageName:
    Default: prod
    Description: The environment name (e.g. dev, prod, etc.)
    Type: String
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs18.x
  Api:
    BinaryMediaTypes:
    - '*~1*'
Resources:
  MidoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: EnvStageName
      Name: mido-api
      Description: Mido API.
    Metadata:
      SamResourceId: MidoApi
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/d7c6e8c5f8eeba15c34b9ffa489142df
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: DummyFunction
  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/fd5dccd52380d3440b410a92d96ea665
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories
            Method: GET
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: GetCategoriesFunction
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/7a8829be247ebe36ef5992dd45a901b4
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /products
            Method: GET
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: GetProductsFunction
  AddProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/75fcf5b06ae72172386a13919447101c
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /products/add
            Method: POST
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: AddProductFunction
  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/8a9e29172bc2dad281e19a942eef82fc
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /products/delete
            Method: DELETE
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: DeleteProductFunction
  AddCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/32e16c85e7e13bd90bb7360de39c0a7f
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories/add
            Method: POST
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: AddCategoryFunction
  DeleteCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/09aca447dd38a216aab33ba68e890dfb
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories/delete
            Method: POST
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: DeleteCategoryFunction
  UpdateCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/41e77299fb97fd0d4c56efdc6b6ff9e2
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories/update
            Method: PUT
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: UpdateCategoryFunction
  GetMasterCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/139038a052e23b753a9d8c3fe7590479
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /master-categories
            Method: GET
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: GetMasterCategoryFunction
  NewsletterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/6d87d9917fd37ad7a99ec5b5e32a64f4
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /newsletter
            Method: POST
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: NewsletterFunction
  HeaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/df73bfb0c8288d921c167b7fdd2fc584
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /headers
            Method: GET
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: HeaderFunction
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/e5408b676e166fae8f18f2dc4be09a72
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /contact-form
            Method: POST
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: ContactFormFunction
  AddTestimonialsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/26ef8692464211ac9251381460cbf9bb
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /add-testimonials
            Method: POST
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: AddTestimonialsFunction
  GetTestimonialsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/97ab49a5a660eae2f3ac2eb189276612
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /get-testimonials
            Method: GET
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: GetTestimonialsFunction
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/299ce6c39df6abaa58a47c47568cc3d0
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /images/upload
            Method: POST
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: UploadImageFunction
  HomePageDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mido-gift-cf-prod-code-deploy/3a5f27d0d76b91a20ef3c88ba14c321a
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        Request:
          Type: Api
          Properties:
            Path: /home
            Method: GET
            RestApiId:
              Ref: MidoApi
    Metadata:
      SamResourceId: HomePageDataFunction
