AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Parameters:
  Region:
    Type: String
    Default: ap-south-1
    Description: The region to deploy the code to.
  EnvStageName:
    Default: dev
    Description: The environment name (e.g. dev, prod, etc.)
    Type: String

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs18.x

Resources:
  MidoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvStageName
      Name: mido-api
      Description: Mido API.
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      # DefinitionBody:
      #   Fn::Transform:
      #     Name: AWS::Include
      #     Parameters:
      #       Location: openapi.yml
      # Body:
      #   swagger: 2.0
      #   info:
      #     version: 0.0.1
      #     title: Mido API
      #   basePath: /
      #   schemes:
      #     - https
      #   definitions:
      #     Empty:
      #       type: object

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/get-categories/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories
            Method: GET
            RestApiId: !Ref MidoApi

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/get-products/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /products
            Method: GET
            RestApiId: !Ref MidoApi

  AddProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/add-product/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /products/add
            Method: POST
            RestApiId: !Ref MidoApi

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/delete-product/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /products/delete
            Method: DELETE
            RestApiId: !Ref MidoApi

  AddCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/add-category/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories/add
            Method: POST
            RestApiId: !Ref MidoApi

  DeleteCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/delete-category/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories/delete
            Method: POST
            RestApiId: !Ref MidoApi
  UpdateCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/update-category/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /categories/update
            Method: PUT
            RestApiId: !Ref MidoApi
  GetMasterCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/get-master-categories/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /master-categories
            Method: GET
            RestApiId: !Ref MidoApi
  NewsletterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/newsletter/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /newsletter
            Method: POST
            RestApiId: !Ref MidoApi
  HeaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/headers/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /headers
            Method: GET
            RestApiId: !Ref MidoApi
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/contact-form/build/src
      Description: Hello World Lambda Function
      MemorySize: 512
      Timeout: 5
      Events:
        Request:
          Type: Api
          Properties:
            Path: /contact-form
            Method: POST
            RestApiId: !Ref MidoApi
